services:
  nginx:
    build:
        context: ./docker
        dockerfile: ./nginx.Dockerfile
        args:
          confFile: "${CONF_FILE}"
    ports:
      - "80:80"
    volumes:
      - ./frontend/dist:/usr/share/nginx/html
    depends_on:
      backend:
        condition: service_started
    networks:
      - app-network

  npm-backend:
    image: node:20
    volumes:
      - ./backend:/app/backend
    working_dir: /app/backend
    command: [ "npm", "install" ]

  npm-frontend:
    image: node:20
    volumes:
      - ./frontend:/app/frontend
    working_dir: /app/frontend
    command: ["npm", "install"]
    depends_on:
      npm-backend:
        condition: service_completed_successfully
  frontend:
    build:
        context: .
        dockerfile: ./docker/frontend.Dockerfile
    volumes:
      - ./frontend:/app/frontend
    ports:
      - "5173:5173"
    depends_on:
      backend:
        condition: service_started
      npm-frontend:
        condition: service_completed_successfully
    networks:
      - app-network
  backend:
    build:
        context: ./docker
        dockerfile: ./backend.Dockerfile
    ports:
      - "9229:9229"
    volumes:
      - ./backend:/app/backend
    depends_on:
      db:
        condition: service_started
      mongodb:
        condition: service_started
      npm-backend:
        condition: service_completed_successfully
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
      - MONGO_URI=mongodb://mongodb/mongo
      - NODE_ENV
    networks:
      - app-network
  db:
    image: postgres:12
    ports:
      - "5433:5432"
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    networks:
      - app-network
  mongodb:
    image: mongo:4
    ports:
      - "27017:27017"
    volumes:
        - mongodb:/data/db
    networks:
      - app-network
volumes:
    db:
    mongodb:
networks:
  app-network:
    driver: bridge