export class EmailTemplate {
    static WELCOME = 1
    static FORGOT_PASSWORD = 2
    static BLOCKED_ACCOUNT = 3
    static PASSWORD_RENEWED = 4
    static PAYMENT_SUCCESS = 5
    static PAYMENT_ERROR = 6    
    static ORDER_SUPPORTED = 7
    static ACCOUNT_ACTIVATED = 8
    static CONFIRM_RESET_PASSWORD = 9
    static OUT_OF_STOCK = 14
    static LOW_STOCK = 17
    static PRODUCT_PRICE_CHANGE = 15
    static NEW_PRODUCT = 16
    static ORDER_STATUS_CHANGED = 18
    static PRODUCT_RESTOCK = 19
    static SUBSCRIBE_NEWSLETTER = 10
    static UNSUBSCRIBE_NEWSLETTER = 13
    static USER_PERSONAL_INFORMATION = 20
}
