name: Deploy to Server

on:
  push:
    branches:
      - main
      - 99-créer-une-action-de-déploiement

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: |
          cd frontend
          ls
          npm install

      - name: Build project
        run: npm run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: frontend-dist
          path: frontend/dist

  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name : install and decode base 64 ssh private key
        run: |
          echo ${{ secrets.SSH_PRIVATE_KEY }} | base64 --decode > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -t rsa ${{ secrets.SERVER_DEPLOY_HOST }} >> ~/.ssh/known_hosts

      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: frontend-dist
          path: frontend/dist

      - name: Deploy to server
        env:
          SERVER_DEPLOY_HOST: ${{ secrets.SERVER_DEPLOY_HOST }}
          SERVER_DEPLOY_USER: ${{ secrets.SERVER_DEPLOY_USER }}
        run: |
          scp -r frontend/dist $SERVER_DEPLOY_USER@$SERVER_DEPLOY_HOST:/root/apagnan-shop/frontend/
        
          ssh -o StrictHostKeyChecking=no $SERVER_DEPLOY_USER@$SERVER_DEPLOY_HOST << 'EOF'
            cd /root/apagnan-shop
            docker compose down
            git pull
            docker compose up -d
            docker compose exec backend npx sequelize-cli db:migrate
            docker compose restart backend
            docker compose stop frontend
          EOF
