name: Deploy to Server

on:
  push:
    branches:
      - main
      - 99-créer-une-action-de-déploiement

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install and Build project
        run: |
          cd frontend
          npm install
          npm run build-only

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: frontend-dist
          path: frontend/dist

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install SSH client and ssh-keyscan
        run: |
          sudo apt-get update
          sudo apt-get install -y openssh-client
          which ssh-keyscan || (sudo apt-get update && sudo apt-get install -y openssh-client)

      - name: Install and decode base64 SSH private key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | base64 --decode > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: frontend-dist
          path: frontend/dist

      - name: Deploy to server
        env:
          SERVER_DEPLOY_HOST: ${{ secrets.SERVER_DEPLOY_HOST }}
          SERVER_DEPLOY_USER: ${{ secrets.SERVER_DEPLOY_USER }}
        run: |
          scp -r frontend/dist $SERVER_DEPLOY_USER@$SERVER_DEPLOY_HOST:/root/apagnan-shop/frontend/
        
          ssh -o StrictHostKeyChecking=no $SERVER_DEPLOY_USER@$SERVER_DEPLOY_HOST << 'EOF'
            cd /root/apagnan-shop
            docker compose down
            git pull
            docker compose up -d
            docker compose exec backend npx sequelize-cli db:migrate
            docker compose restart backend
            docker compose stop frontend
          EOF
